### ISSUE TITLE
Unexpected app name with the `review-apps` endpoint

### ISSUE THREAD

**Issue by Blaked84** [pmbanugo/heroku-review-app-actions#17]
Hello,

first, thank you for this project 👍

I tried to use the last version (2.0.0-dev-1) but the app created using the `review-app` endpoint doesn't have the expected name and url:
- expected: ${{ inputs.base-name }}-pr-${{ github.event.number }}
- actual: ${{ inputs.base-name }}-{branch-name truncated to 15 chars}-{random string}

I'm trying to get the review app url from others api call an I'll open a PR.

**Comment by pmbanugo** [comment]
That part is a little dependent on your settings. You need to set your review app name to be predictable. In your review app settings, you have to use a predictable setting and the unique identifier is what you set as `base-name`. Otherwise, the name is randomly generated and it's not currently handled. Perhaps something I could handle better when I re-write this action using JS.

<img width="383" alt="Screenshot 2022-05-11 at 10 14 08" src="https://user-images.githubusercontent.com/4036118/167801759-86949105-3873-4d57-b82a-8c0cab33c9b7.png">

**Comment by Blaked84** [comment]
Yes, I agree this part is dependent on the settings of my pipeline. But as Heroku disabled the GitHub integration it's not possible any more to enable the review app feature and to access to these setting (or if it's possible, I haven't food yet how).
![image](https://user-images.githubusercontent.com/2858608/167809676-fd149416-8084-4fe1-b212-65120652c7f6.png)

I found a solution by updating the app name... but it's not very elegant: https://github.com/Blaked84/heroku-review-app-actions/blob/main/action.yaml#L82-L104

**Comment by pmbanugo** [comment]
Maybe then v1.2.1 will better suit you because that doesn't use the review apps endpoint. You just create apps that are later added to the pipeline and the values from app.json are handled. The v2 is more suitable for those who already have already review apps enabled.

Would you like to try that instead?

**Comment by Blaked84** [comment]
I tried v1.2.1 yesterday and the name was the expected one in my use case 👍

I just moved the v2 as I've read the `review-apps` endpoind is more reliable.

**Comment by pmbanugo** [comment]
Oh, I meant it's now more reliable because Heroku said they disabled the Review Apps API. v1.2.1 uses a different endpoint and it works.
